### PR TITLE
init: fix repetitive all matching characters.

### PR DESCRIPTION
**Pull request by BeyondMagic**
With a large dictionary, typing multiple '_' will result look to list all words.

You can confirm by executing look on the terminal `look _`, `look ____`, `look __________`,...

This fixes that.

### CODE REVIEW

**Comment by octaltree** [comment]
I don't understand what you are trying to achieve, so please give me a concrete example.
Since all characters except alphabet are affected, there should be an option rather than the default.

**Comment by BeyondMagic** [comment]
Open a terminal.

Run the following commands:

```zsh
$ look _
$ look __
$ look ___
$ look ____
$ look _____
```

See how the output is the same.

The output is all words that `look` can see.

The command though takes some time, it may vary from dictionary to dictionary, but mine is around 500ms.

Now you have `cmp-look`, this plugin which sources all the words that `look` can see, the command, can give.

Every time you type enough characters for the `cmp-look` to run (the option `keyword_length`), `look` will run.

When you're typing something simple like, `sim`, it will list just a few words.

However, when you type `___` it will list all the words (which takes time).

Type again more one `_` and it will take more time.

Type once again and it will take more time.

Some people, like me, make separators using repetitive `_`s, it gives a nice touch when making comments, or just formatting overall.

However, it is impossible to do it because `cmp-look` is synchronous, when you try to type multiple `_`s, it will make `look` run many times creating a really long delay and blocking nvim as whole.

This commit fixes this, it may not be the best way to do it -- but I hope you can give a try fixing into it because it's the only negative point about this plugin.

**Comment by octaltree** [comment]
https://github.com/octaltree/cmp-look/tree/dflag wip
I'm thinking I should specify alphanumeric for keyword_pattern.

**Comment by octaltree** [comment]
The dflag implementation can ignore the _ of keyword_length. If you've specified option.dict, set dflag to true.

Since keyword_pattern is static in ddc I couldn't modify the keyword_pattern to take non-English words into account.

**Pull request merged**
